name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
            ext: .exe
            asset_name: gh-pr-digest.exe
          - os: darwin
            arch: amd64
            ext: ""
            asset_name: gh-pr-digest
          - os: darwin
            arch: arm64
            ext: ""
            asset_name: gh-pr-digest
          - os: linux
            arch: amd64
            ext: ""
            asset_name: gh-pr-digest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o "${{ matrix.asset_name }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gh-pr-digest-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ matrix.asset_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF#refs/tags/}"

          # リリースノートを作成
          echo "## インストール方法" > release_notes.md
          echo "\`\`\`bash" >> release_notes.md
          echo "gh extension install hiroyannnn/gh-pr-digest" >> release_notes.md
          echo "\`\`\`" >> release_notes.md

          # アーティファクトを適切なディレクトリに移動
          mkdir -p release
          for os_arch in dist/*; do
            if [ -d "$os_arch" ]; then
              os_arch_name=$(basename "$os_arch")
              cp "$os_arch"/* "release/${os_arch_name}"
            fi
          done

          # リリースを作成
          gh release create "$tag_name" \
            --title "Release $tag_name" \
            --draft \
            --notes-file release_notes.md \
            ./release/*

      - name: Publish Release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF#refs/tags/}"
          gh release edit "$tag_name" --draft=false

